### ISSUE TITLE
error callback not working

### ISSUE THREAD

**Issue by Crapworks** [vitalets/x-editable#181]
Hi,

first of all, I'm quite new to javascript, jquery, etc. I'm originally a backend developer, so maybe I'm just doing something wrong :)

I have an editable element, and the config looks like this:

``` javascript
    $('.highlight').editable({
        type: 'textarea',    
        inputclass: 'span12',
        url: '/endpoint',  
        send: 'always',
        ajaxOptions: {  
            type: 'put',     
            dataType: 'json',              
            contentType: 'application/json'
        },                        
        params: function(params) {
            return params.value;
        },                        
        display: function(value) {                   
            $(this).html('<pre>' + value + '</pre>');
        },                                     
        success: function(response, newValue) {             
            return { 'newValue': JSON.stringify(response) };
        },                 
        error: function(err) {
            console.log('error');
        }
    });
```

Everything works fine, except the error callback. In case the endpoint returns somethin != 200, it seems that this callback is not invoked. I would like to do something with the json error that comes back as a response, so how can I achieve that?

Regards,
Christian

**Comment by jimeng** [comment]
This remains an issue in 2015.  The x-editable success function works fine, as documented.  But the error function seems to have no effect.  

Using code similar to that shown above (except that the error function returned a string, as the x-editable documentation suggest), the error function is never called when a 400- or 500-level error is encountered.  

Following sr8's suggestion above, I moved the error function to the ajaxOptions, but the return value of that function was ignored by x-editable, and xhr.responseText was being displayed instead.  As a workaround, I set the value of xhr.responseText to the error message I wanted displayed.  

That works.  

It's been nearly two years since this issue was reported.  Maybe it should be reopened.  If nothing else, the documentation could be fixed so it describes the actual behavior of x-editable.  Thanks

**Comment by ins429** [comment]
I noticed that error callback is not being called when validation fails on client-side as well.

**Comment by amfriedman** [comment]
I also notice this problem.

Even when I call it manually in success() with: 
this.error.call(this, response);
... and try to have that function return the error message...

It does not change the behavior of x-editable, which acts as if the edit succeeded and fails to display the error.
