### ISSUE TITLE
how to add "auto-open next field" ability to my app?

### ISSUE THREAD

**Issue by tron52** [vitalets/x-editable#466]
how to activate x-editable's "auto-open next field'? seen in http://vitalets.github.io/x-editable/demo-bs3.html

t

**Comment by theshadow124** [comment]
I am commenting here since this is one of the first google results for me when I was trying to figure out how to go to the next element regardless of form format.

Here is a more generalised way of dealing with finding the next editable field:

```
$("#editable_parent_container .editable:visible").on('hidden', function (e, reason) {
    if (reason === 'save' || reason === 'nochange') {
        var that = this;
        $("#editable_parent_container .editable:visible").eq($("#editable_parent_container .editable:visible").index(that) + 1).editable('show');
    }
});
```

This will increment to the next element with the class "editable" that is visible within the element with id: "editable_parent_container" the editable element does not need to be a direct child, just a child to the parent in some way, this allows for more elegant traversal of a form with many different formatting methods
