### ISSUE TITLE
Newlines in textareas value are not correctly handled

### ISSUE THREAD

**Issue by jmfontaine** [vitalets/x-editable#48]
When newlines ("\n") are present in the HTML value they are left as is by html2value() method.

When the value is converted back to HTML by value2html() the newlines become extra <br> tags.

Example:

Original HTML: `This<br>\nis<br>my<br>sentence`
Transformed value: `This\n\nis\nmy\nsentence`
Transformed HTML: `This<br><br>is<br>my<br>sentence`

**Comment by feliperaul** [comment]
I'm still having this problem.

Using jquery-editable-poshytip.js v1.5.1 

When I load the page I see newlines: 

![image](https://cloud.githubusercontent.com/assets/743879/10988692/e4717aee-8425-11e5-8b32-0bb05ca1bffb.png)

When I click on x-editable, I don't see them inside the textarea:

![image](https://cloud.githubusercontent.com/assets/743879/10988701/fb0a94ca-8425-11e5-8d2d-689a92a5f71f.png)

If I manually insert a newline and save, the next time I open x-editable (if I don't reload the page) it will be correct:

![image](https://cloud.githubusercontent.com/assets/743879/10988714/1a25b150-8426-11e5-8ce5-7e4203bbb50d.png)

And it also saves correctly to the database, because after a page reload I get this:

![image](https://cloud.githubusercontent.com/assets/743879/10988719/29d1b5e0-8426-11e5-89b3-df7f842610fa.png)

But, again, if after reloading the page I click on it ... back to square 0:

![image](https://cloud.githubusercontent.com/assets/743879/10988726/36fe05ac-8426-11e5-8fcb-7838b6d2b7be.png)
