### ISSUE TITLE
bootstrap-editable requires popover.js even in inline mode

### ISSUE THREAD

**Issue by uiliw** [vitalets/x-editable#639]
Im using custom compiled bootstrap without popover.js as i wont use it for my project..
and im using x-editable with inline mode.. but i get an error on my console witch is:

Uncaught TypeError: Cannot read property 'Constructor' of undefined 

when i enable popover.js again, everything works ok!
is there a way to prevent the use o popover.js when using inline mode?

**Comment by pjlegato** [comment]
+1. It shouldn't do anything with popover if it's in inline mode.

**Comment by pchaganti** [comment]
+1

**Comment by ricardofreeman** [comment]
I don't know if your problem is the same as mine (the error on the console is the same) but I solved it by moving the call `<script src="bootstrap-editable/js/bootstrap-editable.js"></script>` to after the core libraries 
```
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
<script src="http://code.jquery.com/jquery-2.0.3.min.js"></script> 
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
```
..as stated on the documentation: http://vitalets.github.io/x-editable/docs.html

It fixed my problem.

**Comment by SeanChense** [comment]
@ricardofreeman you are right

**Comment by Eduardomendesc** [comment]
please include bootstrap.js and try that again
