### ISSUE TITLE
Rails '\n' new line being replaced by white space

### ISSUE THREAD

**Issue by strickland84** [vitalets/x-editable#644]
Wonder if anyone can assist; using Rails 4.1 with x-editable. My textarea inputs are being rendered with '\n' being replaced by white-space. 

Example: database value: "Test\nTest\nTest\n"

Output in 
![screen shot 2014-08-22 at 11 50 29](https://cloud.githubusercontent.com/assets/2702496/4009818/2ca9e202-29ea-11e4-8b07-ce1e4d433fb7.png)

![screen shot 2014-08-22 at 11 50 35](https://cloud.githubusercontent.com/assets/2702496/4009819/30f59d60-29ea-11e4-8c47-0133478c2ece.png)

I have written a method to replace \n with <br> and while that renders correctly, when user activates textarea the <br> are rendered in the input box; so not ideal.

Any ideas? Thanks!

**Comment by bangn** [comment]
+1. I have same problem

**Comment by tobernguyen** [comment]
+1. Confirm having same problem :(
I tried to debug and see that it send params with correct value but when read from database, it failed to parse correctly.


![screen shot 2015-04-08 at 11 46 43 pm](https://cloud.githubusercontent.com/assets/10015525/7050165/8e3ca248-de49-11e4-8d46-79c9144ee233.png)

![screen shot 2015-04-08 at 11 46 51 pm](https://cloud.githubusercontent.com/assets/10015525/7050187/be08116a-de49-11e4-9a39-b06fe6c54673.png)

**Comment by laserlemon** [comment]
I'm using Slim in my Rails 4.2 app, and was seeing this exact issue. It turns out that Slim is doing some kind of nifty indenting to make things pretty (at least in development mode). That means that it's indenting the subsequent lines, even when you don't want them to be. I added this to an initializer and it fixed the issue for me. I don't care for nicely indented HTML anyway.

```ruby
Slim::Engine.options[:pretty] = false
```

Could be a similar issue for HAML too. I don't know. Hope that helps!

**Comment by pabloq** [comment]
Slim::Engine.options[:pretty] = false 

did the trick for me, thanks @laserlemon
