### ISSUE TITLE
X-editable not compatible with select2 3.5.2 ?

### ISSUE THREAD

**Issue by toverux** [vitalets/x-editable#701]
Hello,
I tried to install select2 to use it with x-editable but it seems that there was a breaking compatibility update in select2 library.

I include these files :
`//cdnjs.cloudflare.com/ajax/libs/select2/3.5.2/select2-bootstrap.css`
`//cdnjs.cloudflare.com/ajax/libs/select2/3.5.2/select2.min.js`

Using `select` data-type, works :
![image](https://cloud.githubusercontent.com/assets/1343250/5616383/41174ec0-9504-11e4-9fe4-5341b28a69f0.png)

Using `select2` data-type, doesn't works:
![image](https://cloud.githubusercontent.com/assets/1343250/5616405/67084684-9504-11e4-9b89-cb450c54a853.png)

I have no errors in console.
Same problem if select2 library is included before|after x-editable library.

**Comment by DavidWMarrs** [comment]
Hi, similarly I've noticed an issue if I try to recreate the 'Select2 (dropdown mode)' demo from http://vitalets.github.io/x-editable/demo.html?c=inline using the Bootstrap 2 Form style and the Inline Mode with Select2 3.5.1 or 3.5.2,

The slight changes I've made are 

    $('#country').editable({
        mode: 'inline',
        showbuttons: false,
        source: countries,
        select2: {
            minimumResultsForSearch: -1
        } 
    });

Normally if I have clicked the 'Bahamas' link to have the Select2 field displayed, and then I click the Select2 field to see the options in the drop-down is shown, if I click outside of the Select2 field (to cancel my change (because I've set showbuttons to false)), then the Select2 field disappears, and X-editable reverts back to the 'Bahamas' link.

With the newer versions of Select2 then I have to click once outside of the Select2 field for the options to disappear, and then a second time for the actual Select2 field to disappear and revert back to the 'Bahamas' link.

Thanks,

David

**Comment by toverux** [comment]
Closing this as this is frankly outdated and it bother me to see it in my Issues overview section :)
