### ISSUE TITLE
X-Editable showing same value on PHP foreach

### ISSUE THREAD

**Issue by vertisan** [vitalets/x-editable#875]
I sets X-Editable in my foreach loop but it's getting the same option for all in loop - why?
My loop:
`<td><a href="#" class="status" data-type="select" data-pk="<?php echo $Message->ID; ?>" data-url="<?php echo base_url( 'manage/assign-employee' ); ?>" datatitle="Wybierz pracownika"></a></td>`

JS:
`var SectionPrefix = '<?php echo $CurrentSection; ?>';
        $('.status').editable({
            value: "<?php echo ( $Message->AssignedEmployee != '' ) ? $Message->AssignedEmployee : '- Brak przypisania -'; ?>",
            source: "<?php echo base_url( 'notifications/get-employees/' ); ?>/" + SectionPrefix,
        });`

**Comment by lcherone** [comment]
Firstly its `data-title="Wybierz pracownika"` not `datatitle="Wybierz pracownika"`, and the issue your having with the same value is most likely because your using a class `.status` and its just applying it to all elements with `.status` class on each iteration of your loop, I bet if you looked its always the last value in your foreach which is the final set.
